export const routes = {
  showAnnouncementShow: false,
  showAnnouncementCreate: false,
  showAnnouncementEdit: false,
  showAnnouncementIndexMap: false,
  showAnnouncementIndexList: false,
  showAnnouncementIndexAdded: false,
  announcementId: null,
  showUserCreate: false,
  showUserAuthorize: false,
  showUserShow: false,
  showUserEditPasswordReset: false,
  showUserEditPhoneVerify: false,
  showUserEditAccount: false,
  showVisitorAbout: false,
  showVisitorContact: false,
  showVisitorTermsOfService: false,
  showVisitorCookiesPolicy: false,
  showVisitorPrivacyPolicy: false,
  showVisitorPrivacySettings: false
}
