export const PAGE_TRACK = 'page'
export const PAGE_EDIT_TRACK = 'page/edit'
export const PAGE_SHOW_TRACK = 'page/show'
export const PAGE_INDEX_TRACK = 'page/index'
export const PAGE_INDEX_MANAGE_TRACK = 'page/index/manage'
export const PAGE_NOT_FOUND_TRACK = 'page/not-found'
