import {
  ROOT_TRACK,
  VISITOR_PRIVACY_SETTINGS_TRACK,
  VISITOR_COOKIES_POLICY_TRACK,
  VISITOR_PRIVACY_POLICY_TRACK,
  VISITOR_TERMS_OF_SERVICE_TRACK,
  VISITOR_CONTACT_TRACK,
  PAGE_CREATE_TRACK,
  PAGE_INDEX_MAP_TRACK,
  PAGE_SHOW_TRACK,
  ANNOUNCEMENT_CREATE_TRACK,
  ANNOUNCEMENT_EDIT_TRACK,
  ANNOUNCEMENT_INDEX_CATALOGUE_TRACK,
  ANNOUNCEMENT_INDEX_MY_TRACK,
  USER_CREATE_TRACK,
  USER_AUTHORIZE_TRACK,
  USER_RESET_PASSWORD_TRACK,
  USER_EDIT_TRACK,
  USER_SHOW_TRACK
} from '../tracks/tracks'

const GENERIC_SENDER = 'genericSender'
const ROOT_SENDER = 'rootSender'
const PAGE_INDEX_MAP_SENDER = 'pageIndexMapSender'
const PAGE_SHOW_SENDER = 'pageShowSender'
const ANNOUNCEMENT_CREATE_SENDER = 'announcementCreateSender'
const ANNOUNCEMENT_INDEX_CATALOGUE_SENDER = 'announcementIndexCatalogueSender'

export default {
  [ROOT_TRACK]: ROOT_SENDER,
  [VISITOR_PRIVACY_SETTINGS_TRACK]: GENERIC_SENDER,
  [VISITOR_COOKIES_POLICY_TRACK]: GENERIC_SENDER,
  [VISITOR_PRIVACY_POLICY_TRACK]: GENERIC_SENDER,
  [VISITOR_TERMS_OF_SERVICE_TRACK]: GENERIC_SENDER,
  [VISITOR_CONTACT_TRACK]: GENERIC_SENDER,
  [PAGE_CREATE_TRACK]: GENERIC_SENDER,
  [PAGE_INDEX_MAP_TRACK]: PAGE_INDEX_MAP_SENDER,
  [PAGE_SHOW_TRACK]: PAGE_SHOW_SENDER,
  [ANNOUNCEMENT_CREATE_TRACK]: ANNOUNCEMENT_CREATE_SENDER,
  [ANNOUNCEMENT_EDIT_TRACK]: GENERIC_SENDER,
  [ANNOUNCEMENT_INDEX_CATALOGUE_TRACK]: ANNOUNCEMENT_INDEX_CATALOGUE_SENDER,
  [ANNOUNCEMENT_INDEX_MY_TRACK]: GENERIC_SENDER,
  [USER_CREATE_TRACK]: GENERIC_SENDER,
  [USER_AUTHORIZE_TRACK]: GENERIC_SENDER,
  [USER_RESET_PASSWORD_TRACK]: GENERIC_SENDER,
  [USER_EDIT_TRACK]: GENERIC_SENDER,
  [USER_SHOW_TRACK]: GENERIC_SENDER
}
