import {
  ROOT_TRACK,
  PAGE_TRACK,
  PAGE_CREATE_TRACK,
  PAGE_EDIT_TRACK,
  PAGE_INDEX_TRACK,
  PAGE_INDEX_MAP_TRACK,
  PAGE_INDEX_MANAGE_TRACK,
  PAGE_SHOW_TRACK,
  PAGE_NOT_FOUND_TRACK,
  VISITOR_TRACK,
  VISITOR_PRIVACY_MONIT_TRACK,
  VISITOR_PRIVACY_SETTINGS_TRACK,
  VISITOR_COOKIES_POLICY_TRACK,
  VISITOR_PRIVACY_POLICY_TRACK,
  VISITOR_TERMS_OF_SERVICE_TRACK,
  VISITOR_CONTACT_TRACK,
  ANNOUNCEMENT_TRACK,
  ANNOUNCEMENT_CREATE_TRACK,
  ANNOUNCEMENT_CREATE_FORM_TRACK,
  ANNOUNCEMENT_CREATE_VERIFICATION_TRACK,
  ANNOUNCEMENT_CREATE_SUCCESS_TRACK,
  ANNOUNCEMENT_CREATE_EDIT_TRACK,
  ANNOUNCEMENT_INDEX_TRACK,
  ANNOUNCEMENT_INDEX_MAP_TRACK,
  ANNOUNCEMENT_INDEX_MAP_APARTMENTS_TRACK,
  ANNOUNCEMENT_INDEX_MAP_HOUSES_TRACK,
  ANNOUNCEMENT_INDEX_MAP_ROOMS_TRACK,
  ANNOUNCEMENT_INDEX_MAP_PARKING_SPACES_TRACK,
  ANNOUNCEMENT_INDEX_MAP_USABLE_PREMISES_TRACK,
  ANNOUNCEMENT_INDEX_MAP_OFFICES_TRACK,
  ANNOUNCEMENT_INDEX_MAP_VIRTUAL_OFFICES_TRACK,
  ANNOUNCEMENT_INDEX_MAP_COWORKING_TRACK,
  ANNOUNCEMENT_INDEX_CATALOGUE_TRACK,
  ANNOUNCEMENT_INDEX_CATALOGUE_APARTMENTS_TRACK,
  ANNOUNCEMENT_INDEX_CATALOGUE_HOUSES_TRACK,
  ANNOUNCEMENT_INDEX_CATALOGUE_ROOMS_TRACK,
  ANNOUNCEMENT_INDEX_CATALOGUE_PARKING_SPACES_TRACK,
  ANNOUNCEMENT_INDEX_CATALOGUE_USABLE_PREMISES_TRACK,
  ANNOUNCEMENT_INDEX_CATALOGUE_OFFICES_TRACK,
  ANNOUNCEMENT_INDEX_CATALOGUE_VIRTUAL_OFFICES_TRACK,
  ANNOUNCEMENT_INDEX_CATALOGUE_COWORKING_TRACK,
  ANNOUNCEMENT_INDEX_MY_TRACK,
  ANNOUNCEMENT_SHOW_TRACK,
  USER_TRACK,
  USER_CREATE_TRACK,
  USER_CREATE_FORM_TRACK,
  USER_CREATE_VERIFICATION_TRACK,
  USER_AUTHORIZE_TRACK,
  USER_EDIT_PASSWORD_TRACK,
  USER_EDIT_TRACK,
  USER_SHOW_TRACK
} from '../tracks/tracks'

export default {
  [ROOT_TRACK]: {
    [VISITOR_TRACK]: true,
    [ANNOUNCEMENT_TRACK]: true,
    [ANNOUNCEMENT_INDEX_TRACK]: true,
    [ANNOUNCEMENT_INDEX_MAP_TRACK]: true,
    [PAGE_TRACK]: true,
    [PAGE_SHOW_TRACK]: true
  },
  [VISITOR_PRIVACY_SETTINGS_TRACK]: {
    [VISITOR_TRACK]: true,
    [VISITOR_PRIVACY_MONIT_TRACK]: false
  },
  [VISITOR_COOKIES_POLICY_TRACK]: {
    [VISITOR_TRACK]: true,
    [VISITOR_PRIVACY_MONIT_TRACK]: false
  },
  [VISITOR_PRIVACY_POLICY_TRACK]: {
    [VISITOR_TRACK]: true,
    [VISITOR_PRIVACY_MONIT_TRACK]: false
  },
  [VISITOR_TERMS_OF_SERVICE_TRACK]: {
    [VISITOR_TRACK]: true,
    [VISITOR_PRIVACY_MONIT_TRACK]: false
  },
  [VISITOR_CONTACT_TRACK]: {
    [VISITOR_TRACK]: true
  },
  [PAGE_CREATE_TRACK]: {
    [VISITOR_TRACK]: true,
    [PAGE_TRACK]: true
  },
  [PAGE_EDIT_TRACK]: {
    [VISITOR_TRACK]: true,
    [PAGE_TRACK]: true
  },
  [PAGE_INDEX_MAP_TRACK]: {
    [VISITOR_TRACK]: true,
    [PAGE_TRACK]: true,
    [PAGE_INDEX_TRACK]: true
  },
  [PAGE_INDEX_MANAGE_TRACK]: {
    [VISITOR_TRACK]: true,
    [PAGE_TRACK]: true,
    [PAGE_INDEX_TRACK]: true
  },
  [PAGE_SHOW_TRACK]: {
    [VISITOR_TRACK]: true,
    [PAGE_TRACK]: true
  },
  [PAGE_NOT_FOUND_TRACK]: {
    [VISITOR_TRACK]: true,
    [PAGE_TRACK]: true
  },
  [ANNOUNCEMENT_CREATE_FORM_TRACK]: {
    [ANNOUNCEMENT_TRACK]: true,
    [ANNOUNCEMENT_CREATE_TRACK]: true,
    [PAGE_TRACK]: true,
    [PAGE_SHOW_TRACK]: true,
    [VISITOR_TRACK]: true
  },
  [ANNOUNCEMENT_CREATE_VERIFICATION_TRACK]: {
    [ANNOUNCEMENT_TRACK]: true,
    [ANNOUNCEMENT_CREATE_TRACK]: true,
    [VISITOR_TRACK]: true
  },
  [ANNOUNCEMENT_CREATE_SUCCESS_TRACK]: {
    [ANNOUNCEMENT_TRACK]: true,
    [ANNOUNCEMENT_CREATE_TRACK]: true,
    [VISITOR_TRACK]: true
  },
  [ANNOUNCEMENT_CREATE_EDIT_TRACK]: {
    [ANNOUNCEMENT_TRACK]: true,
    [ANNOUNCEMENT_CREATE_TRACK]: true,
    [VISITOR_TRACK]: true,
  },
  [ANNOUNCEMENT_INDEX_MAP_APARTMENTS_TRACK]: {
    [VISITOR_TRACK]: true,
    [ANNOUNCEMENT_TRACK]: true,
    [ANNOUNCEMENT_INDEX_TRACK]: true,
    [ANNOUNCEMENT_INDEX_MAP_TRACK]: true
  },
  [ANNOUNCEMENT_INDEX_MAP_HOUSES_TRACK]: {
    [VISITOR_TRACK]: true,
    [ANNOUNCEMENT_TRACK]: true,
    [ANNOUNCEMENT_INDEX_TRACK]: true,
    [ANNOUNCEMENT_INDEX_MAP_TRACK]: true
  },
  [ANNOUNCEMENT_INDEX_MAP_ROOMS_TRACK]: {
    [VISITOR_TRACK]: true,
    [ANNOUNCEMENT_TRACK]: true,
    [ANNOUNCEMENT_INDEX_TRACK]: true,
    [ANNOUNCEMENT_INDEX_MAP_TRACK]: true
  },
  [ANNOUNCEMENT_INDEX_MAP_PARKING_SPACES_TRACK]: {
    [VISITOR_TRACK]: true,
    [ANNOUNCEMENT_TRACK]: true,
    [ANNOUNCEMENT_INDEX_TRACK]: true,
    [ANNOUNCEMENT_INDEX_MAP_TRACK]: true
  },
  [ANNOUNCEMENT_INDEX_MAP_USABLE_PREMISES_TRACK]: {
    [VISITOR_TRACK]: true,
    [ANNOUNCEMENT_TRACK]: true,
    [ANNOUNCEMENT_INDEX_TRACK]: true,
    [ANNOUNCEMENT_INDEX_MAP_TRACK]: true
  },
  [ANNOUNCEMENT_INDEX_MAP_OFFICES_TRACK]: {
    [VISITOR_TRACK]: true,
    [ANNOUNCEMENT_TRACK]: true,
    [ANNOUNCEMENT_INDEX_TRACK]: true,
    [ANNOUNCEMENT_INDEX_MAP_TRACK]: true
  },
  [ANNOUNCEMENT_INDEX_MAP_VIRTUAL_OFFICES_TRACK]: {
    [VISITOR_TRACK]: true,
    [ANNOUNCEMENT_TRACK]: true,
    [ANNOUNCEMENT_INDEX_TRACK]: true,
    [ANNOUNCEMENT_INDEX_MAP_TRACK]: true
  },
  [ANNOUNCEMENT_INDEX_MAP_COWORKING_TRACK]: {
    [VISITOR_TRACK]: true,
    [ANNOUNCEMENT_TRACK]: true,
    [ANNOUNCEMENT_INDEX_TRACK]: true,
    [ANNOUNCEMENT_INDEX_MAP_TRACK]: true
  },
  [ANNOUNCEMENT_INDEX_CATALOGUE_TRACK]: {
    [VISITOR_TRACK]: true,
    [ANNOUNCEMENT_TRACK]: true,
    [ANNOUNCEMENT_INDEX_TRACK]: true,
    [ANNOUNCEMENT_INDEX_MAP_TRACK]: true
  },
  [ANNOUNCEMENT_INDEX_CATALOGUE_APARTMENTS_TRACK]: {
    [VISITOR_TRACK]: true,
    [ANNOUNCEMENT_TRACK]: true,
    [ANNOUNCEMENT_INDEX_TRACK]: true,
    [ANNOUNCEMENT_INDEX_CATALOGUE_TRACK]: true
  },
  [ANNOUNCEMENT_INDEX_CATALOGUE_HOUSES_TRACK]: {
    [VISITOR_TRACK]: true,
    [ANNOUNCEMENT_TRACK]: true,
    [ANNOUNCEMENT_INDEX_TRACK]: true,
    [ANNOUNCEMENT_INDEX_CATALOGUE_TRACK]: true
  },
  [ANNOUNCEMENT_INDEX_CATALOGUE_ROOMS_TRACK]: {
    [VISITOR_TRACK]: true,
    [ANNOUNCEMENT_TRACK]: true,
    [ANNOUNCEMENT_INDEX_TRACK]: true,
    [ANNOUNCEMENT_INDEX_CATALOGUE_TRACK]: true
  },
  [ANNOUNCEMENT_INDEX_CATALOGUE_PARKING_SPACES_TRACK]: {
    [VISITOR_TRACK]: true,
    [ANNOUNCEMENT_TRACK]: true,
    [ANNOUNCEMENT_INDEX_TRACK]: true,
    [ANNOUNCEMENT_INDEX_CATALOGUE_TRACK]: true
  },
  [ANNOUNCEMENT_INDEX_CATALOGUE_USABLE_PREMISES_TRACK]: {
    [VISITOR_TRACK]: true,
    [ANNOUNCEMENT_TRACK]: true,
    [ANNOUNCEMENT_INDEX_TRACK]: true,
    [ANNOUNCEMENT_INDEX_CATALOGUE_TRACK]: true
  },
  [ANNOUNCEMENT_INDEX_CATALOGUE_OFFICES_TRACK]: {
    [VISITOR_TRACK]: true,
    [ANNOUNCEMENT_TRACK]: true,
    [ANNOUNCEMENT_INDEX_TRACK]: true,
    [ANNOUNCEMENT_INDEX_CATALOGUE_TRACK]: true
  },
  [ANNOUNCEMENT_INDEX_CATALOGUE_VIRTUAL_OFFICES_TRACK]: {
    [VISITOR_TRACK]: true,
    [ANNOUNCEMENT_TRACK]: true,
    [ANNOUNCEMENT_INDEX_TRACK]: true,
    [ANNOUNCEMENT_INDEX_CATALOGUE_TRACK]: true
  },
  [ANNOUNCEMENT_INDEX_CATALOGUE_COWORKING_TRACK]: {
    [VISITOR_TRACK]: true,
    [ANNOUNCEMENT_TRACK]: true,
    [ANNOUNCEMENT_INDEX_TRACK]: true,
    [ANNOUNCEMENT_INDEX_CATALOGUE_TRACK]: true
  },
  [ANNOUNCEMENT_INDEX_MY_TRACK]: {
    [VISITOR_TRACK]: true,
    [ANNOUNCEMENT_TRACK]: true,
    [ANNOUNCEMENT_INDEX_TRACK]: true
  },
  [ANNOUNCEMENT_SHOW_TRACK]: {
    [VISITOR_TRACK]: true,
    [ANNOUNCEMENT_TRACK]: true
  },
  [USER_CREATE_FORM_TRACK]: {
    [USER_TRACK]: true,
    [USER_CREATE_TRACK]: true,
    [VISITOR_TRACK]: true
  },
  [USER_CREATE_VERIFICATION_TRACK]: {
    [USER_TRACK]: true,
    [USER_CREATE_TRACK]: true,
    [VISITOR_TRACK]: true,
    [USER_TRACK]: true
  },
  [USER_AUTHORIZE_TRACK]: {
    [VISITOR_TRACK]: true,
    [USER_TRACK]: true
  },
  [USER_EDIT_PASSWORD_TRACK]: {
    [VISITOR_TRACK]: true,
    [USER_TRACK]: true
  },
  [USER_EDIT_TRACK]: {
    [VISITOR_TRACK]: true,
    [USER_TRACK]: true
  },
  [USER_SHOW_TRACK]: {
    [VISITOR_TRACK]: true,
    [USER_TRACK]: true
  }
}
