import {
  PL,
  EN
} from '../langs/langs'

import {
  ROOT_URLS,
  VISITOR_PRIVACY_SETTINGS_URLS,
  VISITOR_COOKIES_POLICY_URLS,
  VISITOR_PRIVACY_POLICY_URLS,
  VISITOR_TERMS_OF_SERVICE_URLS,
  VISITOR_CONTACT_URLS,
  PAGE_CREATE_URLS,
  PAGE_INDEX_MAP_URLS,
  ANNOUNCEMENT_CREATE_URLS,
  ANNOUNCEMENT_EDIT_URLS,
  ANNOUNCEMENT_INDEX_MAP_URLS,
  ANNOUNCEMENT_INDEX_CATALOGUE_URLS,
  ANNOUNCEMENT_INDEX_MY_URLS,
  ANNOUNCEMENT_SHOW_URLS,
  USER_CREATE_URLS,
  USER_AUTHORIZE_URLS,
  USER_RESET_PASSWORD_URLS,
  USER_EDIT_URLS,
  USER_SHOW_URLS
} from './urls'

import {
  ROOT_TRACK,
  VISITOR_PRIVACY_SETTINGS_TRACK,
  VISITOR_COOKIES_POLICY_TRACK,
  VISITOR_PRIVACY_POLICY_TRACK,
  VISITOR_TERMS_OF_SERVICE_TRACK,
  VISITOR_CONTACT_TRACK,
  PAGE_CREATE_TRACK,
  PAGE_INDEX_MAP_TRACK,
  ANNOUNCEMENT_CREATE_TRACK,
  ANNOUNCEMENT_EDIT_TRACK,
  ANNOUNCEMENT_INDEX_MAP_TRACK,
  ANNOUNCEMENT_INDEX_CATALOGUE_TRACK,
  ANNOUNCEMENT_INDEX_MY_TRACK,
  ANNOUNCEMENT_SHOW_TRACK,
  USER_CREATE_TRACK,
  USER_EDIT_TRACK,
  USER_RESET_PASSWORD_TRACK,
  USER_AUTHORIZE_TRACK,
  USER_SHOW_TRACK
} from '../tracks/tracks'

export default [
  {
    url: ROOT_URLS,
    track: ROOT_TRACK,
    lang: PL
  },
  {
    url: VISITOR_PRIVACY_SETTINGS_URLS[PL],
    track: VISITOR_PRIVACY_SETTINGS_TRACK,
    lang: PL
  },
  {
    url: VISITOR_PRIVACY_SETTINGS_URLS[EN],
    track: VISITOR_PRIVACY_SETTINGS_TRACK,
    lang: EN
  },
  {
    url: VISITOR_COOKIES_POLICY_URLS[PL],
    track: VISITOR_COOKIES_POLICY_TRACK,
    lang: PL
  },
  {
    url: VISITOR_COOKIES_POLICY_URLS[EN],
    track: VISITOR_COOKIES_POLICY_TRACK,
    lang: EN
  },
  {
    url: VISITOR_PRIVACY_POLICY_URLS[PL],
    track: VISITOR_PRIVACY_POLICY_TRACK,
    lang: PL
  },
  {
    url: VISITOR_PRIVACY_POLICY_URLS[EN],
    track: VISITOR_PRIVACY_POLICY_TRACK,
    lang: EN
  },
  {
    url: VISITOR_TERMS_OF_SERVICE_URLS[PL],
    track: VISITOR_TERMS_OF_SERVICE_TRACK,
    lang: PL
  },
  {
    url: VISITOR_TERMS_OF_SERVICE_URLS[EN],
    track: VISITOR_TERMS_OF_SERVICE_TRACK,
    lang: EN
  },
  {
    url: VISITOR_CONTACT_URLS[PL],
    track: VISITOR_CONTACT_TRACK,
    lang: PL
  },
  {
    url: VISITOR_CONTACT_URLS[EN],
    track: VISITOR_CONTACT_TRACK,
    lang: EN
  },
  {
    url: PAGE_CREATE_URLS[PL],
    track: PAGE_CREATE_TRACK,
    lang: PL
  },
  {
    url: PAGE_CREATE_URLS[EN],
    track: PAGE_CREATE_TRACK,
    lang: EN
  },
  {
    url: PAGE_INDEX_MAP_URLS[PL],
    track: PAGE_INDEX_MAP_TRACK,
    lang: PL
  },
  {
    url: PAGE_INDEX_MAP_URLS[EN],
    track: PAGE_INDEX_MAP_TRACK,
    lang: EN
  },
  {
    url: ANNOUNCEMENT_CREATE_URLS[PL],
    track: ANNOUNCEMENT_CREATE_TRACK,
    lang: PL
  },
  {
    url: ANNOUNCEMENT_CREATE_URLS[EN],
    track: ANNOUNCEMENT_CREATE_TRACK,
    lang: EN
  },
  {
    url: ANNOUNCEMENT_EDIT_URLS[PL],
    track: ANNOUNCEMENT_EDIT_TRACK,
    lang: PL,
    withWildcards: true
  },
  {
    url: ANNOUNCEMENT_EDIT_URLS[EN],
    track: ANNOUNCEMENT_EDIT_TRACK,
    lang: EN,
    withWildcards: true
  },
  {
    url: ANNOUNCEMENT_INDEX_MAP_URLS[PL],
    track: ANNOUNCEMENT_INDEX_MAP_TRACK,
    lang: PL
  },
  {
    url: ANNOUNCEMENT_INDEX_MAP_URLS[EN],
    track: ANNOUNCEMENT_INDEX_MAP_TRACK,
    lang: EN
  },
  {
    url: ANNOUNCEMENT_INDEX_CATALOGUE_URLS[PL],
    track: ANNOUNCEMENT_INDEX_CATALOGUE_TRACK,
    lang: PL
  },
  {
    url: ANNOUNCEMENT_INDEX_CATALOGUE_URLS[EN],
    track: ANNOUNCEMENT_INDEX_CATALOGUE_TRACK,
    lang: EN
  },
  {
    url: ANNOUNCEMENT_INDEX_MY_URLS[PL],
    track: ANNOUNCEMENT_INDEX_MY_TRACK,
    lang: PL
  },
  {
    url: ANNOUNCEMENT_INDEX_MY_URLS[EN],
    track: ANNOUNCEMENT_INDEX_MY_TRACK,
    lang: EN
  },
  {
    url: ANNOUNCEMENT_SHOW_URLS[PL],
    track: ANNOUNCEMENT_SHOW_TRACK,
    lang: PL,
    withWildcards: true
  },
  {
    url: ANNOUNCEMENT_SHOW_URLS[EN],
    track: ANNOUNCEMENT_SHOW_TRACK,
    lang: EN,
    withWildcards: true
  },
  {
    url: USER_CREATE_URLS[PL],
    track: USER_CREATE_TRACK,
    lang: PL
  },
  {
    url: USER_CREATE_URLS[EN],
    track: USER_CREATE_TRACK,
    lang: EN
  },
  {
    url: USER_AUTHORIZE_URLS[PL],
    track: USER_AUTHORIZE_TRACK,
    lang: PL
  },
  {
    url: USER_AUTHORIZE_URLS[EN],
    track: USER_AUTHORIZE_TRACK,
    lang: EN
  },
  {
    url: USER_RESET_PASSWORD_URLS[PL],
    track: USER_RESET_PASSWORD_TRACK,
    lang: PL
  },
  {
    url: USER_RESET_PASSWORD_URLS[EN],
    track: USER_RESET_PASSWORD_TRACK,
    lang: EN
  },
  {
    url: USER_EDIT_URLS[PL],
    track: USER_EDIT_TRACK,
    lang: PL
  },
  {
    url: USER_EDIT_URLS[EN],
    track: USER_EDIT_TRACK,
    lang: EN
  },
  {
    url: USER_SHOW_URLS[PL],
    track: USER_SHOW_TRACK,
    lang: PL
  },
  {
    url: USER_SHOW_URLS[EN],
    track: USER_SHOW_TRACK,
    lang: EN
  }
]
