import {
  PL,
  EN
} from '../langs/langs'

import {
  ROOT_URL,
  VISITOR_PRIVACY_SETTINGS_URL_PL,
  VISITOR_PRIVACY_SETTINGS_URL_EN,
  VISITOR_COOKIES_POLICY_URL_PL,
  VISITOR_COOKIES_POLICY_URL_EN,
  VISITOR_PRIVACY_POLICY_URL_PL,
  VISITOR_PRIVACY_POLICY_URL_EN,
  VISITOR_TERMS_OF_SERVICE_URL_PL,
  VISITOR_TERMS_OF_SERVICE_URL_EN,
  VISITOR_CONTACT_URL_PL,
  VISITOR_CONTACT_URL_EN,
  PAGE_CREATE_URL_PL,
  PAGE_CREATE_URL_EN,
  PAGE_INDEX_MAP_URL_PL,
  PAGE_INDEX_MAP_URL_EN,
  ANNOUNCEMENT_CREATE_URL_PL,
  ANNOUNCEMENT_CREATE_URL_EN,
  ANNOUNCEMENT_EDIT_URL_PL,
  ANNOUNCEMENT_EDIT_URL_EN,
  ANNOUNCEMENT_INDEX_MAP_URL_PL,
  ANNOUNCEMENT_INDEX_MAP_URL_EN,
  ANNOUNCEMENT_INDEX_CATALOGUE_URL_PL,
  ANNOUNCEMENT_INDEX_CATALOGUE_URL_EN,
  ANNOUNCEMENT_INDEX_MY_URL_PL,
  ANNOUNCEMENT_INDEX_MY_URL_EN,
  ANNOUNCEMENT_SHOW_URL_PL,
  ANNOUNCEMENT_SHOW_URL_EN,
  USER_CREATE_URL_PL,
  USER_CREATE_URL_EN,
  USER_AUTHORIZE_URL_PL,
  USER_AUTHORIZE_URL_EN,
  USER_RESET_PASSWORD_URL_PL,
  USER_RESET_PASSWORD_URL_EN,
  USER_EDIT_URL_PL,
  USER_EDIT_URL_EN,
  USER_SHOW_URL_PL,
  USER_SHOW_URL_EN
} from './urls'

import {
  ROOT_TRACK,
  VISITOR_PRIVACY_SETTINGS,
  VISITOR_COOKIES_POLICY,
  VISITOR_PRIVACY_POLICY,
  VISITOR_TERMS_OF_SERVICE,
  VISITOR_CONTACT,
  PAGE_CREATE,
  PAGE_INDEX_MAP,
  ANNOUNCEMENT_CREATE,
  ANNOUNCEMENT_EDIT,
  ANNOUNCEMENT_INDEX_MAP,
  ANNOUNCEMENT_INDEX_CATALOGUE,
  ANNOUNCEMENT_INDEX_MY,
  ANNOUNCEMENT_SHOW,
  USER_CREATE,
  USER_EDIT,
  USER_RESET_PASSWORD,
  USER_AUTHORIZE,
  USER_SHOW
} from '../tracks/tracks'

export default [
  {
    url: ROOT_URL,
    track: ROOT_TRACK,
    lang: PL
  },
  {
    url: VISITOR_PRIVACY_SETTINGS_URL_PL,
    track: VISITOR_PRIVACY_SETTINGS,
    lang: PL
  },
  {
    url: VISITOR_PRIVACY_SETTINGS_URL_EN,
    track: VISITOR_PRIVACY_SETTINGS,
    lang: EN
  },
  {
    url: VISITOR_COOKIES_POLICY_URL_PL,
    track: VISITOR_COOKIES_POLICY,
    lang: PL
  },
  {
    url: VISITOR_COOKIES_POLICY_URL_EN,
    track: VISITOR_COOKIES_POLICY,
    lang: EN
  },
  {
    url: VISITOR_PRIVACY_POLICY_URL_PL,
    track: VISITOR_PRIVACY_POLICY,
    lang: PL
  },
  {
    url: VISITOR_PRIVACY_POLICY_URL_EN,
    track: VISITOR_PRIVACY_POLICY,
    lang: EN
  },
  {
    url: VISITOR_TERMS_OF_SERVICE_URL_PL,
    track: VISITOR_TERMS_OF_SERVICE,
    lang: PL
  },
  {
    url: VISITOR_TERMS_OF_SERVICE_URL_EN,
    track: VISITOR_TERMS_OF_SERVICE,
    lang: EN
  },
  {
    url: VISITOR_CONTACT_URL_PL,
    track: VISITOR_CONTACT,
    lang: PL
  },
  {
    url: VISITOR_CONTACT_URL_EN,
    track: VISITOR_CONTACT,
    lang: EN
  },
  {
    url: PAGE_CREATE_URL_PL,
    track: PAGE_CREATE,
    lang: PL
  },
  {
    url: PAGE_CREATE_URL_EN,
    track: PAGE_CREATE,
    lang: EN
  },
  {
    url: PAGE_INDEX_MAP_URL_PL,
    track: PAGE_INDEX_MAP,
    lang: PL
  },
  {
    url: PAGE_INDEX_MAP_URL_EN,
    track: PAGE_INDEX_MAP,
    lang: EN
  },
  {
    url: ANNOUNCEMENT_CREATE_URL_PL,
    track: ANNOUNCEMENT_CREATE,
    lang: PL
  },
  {
    url: ANNOUNCEMENT_CREATE_URL_EN,
    track: ANNOUNCEMENT_CREATE,
    lang: EN
  },
  {
    url: ANNOUNCEMENT_EDIT_URL_PL,
    track: ANNOUNCEMENT_EDIT,
    lang: PL,
    withWildcards: true
  },
  {
    url: ANNOUNCEMENT_EDIT_URL_EN,
    track: ANNOUNCEMENT_EDIT,
    lang: EN,
    withWildcards: true
  },
  {
    url: ANNOUNCEMENT_INDEX_MAP_URL_PL,
    track: ANNOUNCEMENT_INDEX_MAP,
    lang: PL
  },
  {
    url: ANNOUNCEMENT_INDEX_MAP_URL_EN,
    track: ANNOUNCEMENT_INDEX_MAP,
    lang: EN
  },
  {
    url: ANNOUNCEMENT_INDEX_CATALOGUE_URL_PL,
    track: ANNOUNCEMENT_INDEX_CATALOGUE,
    lang: PL
  },
  {
    url: ANNOUNCEMENT_INDEX_CATALOGUE_URL_EN,
    track: ANNOUNCEMENT_INDEX_CATALOGUE,
    lang: EN
  },
  {
    url: ANNOUNCEMENT_INDEX_MY_URL_PL,
    track: ANNOUNCEMENT_INDEX_MY,
    lang: PL
  },
  {
    url: ANNOUNCEMENT_INDEX_MY_URL_EN,
    track: ANNOUNCEMENT_INDEX_MY,
    lang: EN
  },
  {
    url: ANNOUNCEMENT_SHOW_URL_PL,
    track: ANNOUNCEMENT_SHOW,
    lang: PL,
    withWildcards: true
  },
  {
    url: ANNOUNCEMENT_SHOW_URL_EN,
    track: ANNOUNCEMENT_SHOW,
    lang: EN,
    withWildcards: true
  },
  {
    url: USER_CREATE_URL_PL,
    track: USER_CREATE,
    lang: PL
  },
  {
    url: USER_CREATE_URL_EN,
    track: USER_CREATE,
    lang: EN
  },
  {
    url: USER_AUTHORIZE_URL_PL,
    track: USER_AUTHORIZE,
    lang: PL
  },
  {
    url: USER_AUTHORIZE_URL_EN,
    track: USER_AUTHORIZE,
    lang: EN
  },
  {
    url: USER_RESET_PASSWORD_URL_PL,
    track: USER_RESET_PASSWORD,
    lang: PL
  },
  {
    url: USER_RESET_PASSWORD_URL_EN,
    track: USER_RESET_PASSWORD,
    lang: EN
  },
  {
    url: USER_EDIT_URL_PL,
    track: USER_EDIT,
    lang: PL
  },
  {
    url: USER_EDIT_URL_EN,
    track: USER_EDIT,
    lang: EN
  },
  {
    url: USER_SHOW_URL_PL,
    track: USER_SHOW,
    lang: PL
  },
  {
    url: USER_SHOW_URL_EN,
    track: USER_SHOW,
    lang: EN
  }
]
