

export const PAGE_CREATE = 'pages/create'
export const PAGE_INDEX_MAP = 'pages/index/map'
export const VISITOR_COOKIES_POLICY = 'visitor/cookies-policy'
export const VISITOR_PRIVACY_SETTINGS = 'visitor/privacy-settings'
export const VISITOR_TERMS_OF_SERVICE = 'visitor/terms-of-service'
export const VISITOR_PRIVACY_POLICY = 'visitor/privacy-policy'
export const VISITOR_CONTACT = 'visitor/contact'
export const ANNOUNCEMENT_INDEX_MAP = 'announcement/index/map'
export const ANNOUNCEMENT_INDEX_CATALOGUE = 'announcement/index/catalogue'
export const ANNOUNCEMENT_INDEX_MY = 'announcement/index/list'
export const ANNOUNCEMENT_SHOW = 'announcement/show'
export const ANNOUNCEMENT_CREATE = 'announcement/create'
export const ANNOUNCEMENT_EDIT = 'announcement/edit'
export const USER_CREATE = 'users/create'
export const USER_RESET_PASSWORD = 'user/edit/password'
export const USER_EDIT = 'user/edit/settings'
export const USER_AUTHORIZE = 'users/authorize'

