export const features = [
  { ref: 'undergroundgarage', polish: 'garaż podziemny', english: 'underground Garage' },
  { ref: 'highceilings', polish: 'wysokie sufity', english: 'high ceilings' },
  { ref: 'wellcommunicated', polish: 'dobrze skomunikowane', english: 'well communicated' },
  { ref: 'standalonegarage', polish: 'garaz wolnostojący', english: 'standalone garage' },
  { ref: 'parkingspaces', polish: 'miejsca postojowe', english: 'parking spaces' },
  { ref: 'entryphone', polish: 'domofon', english: 'entry phone' },
  { ref: 'monitoring', polish: 'monitoring', english: 'video surveillance' },
  { ref: 'lifts', polish: 'windy', english: 'lifts' },
  { ref: 'renovatedbuilding', polish: 'odremontowany budynek', english: 'renovated building' },
  { ref: 'renovatedcommonareas', polish: 'odremontowane części wspólne', english: 'renovated commona reas' },
  { ref: 'highspeedelevator', polish: 'szybka winda', english: 'high-speed elevator' },
  { ref: 'classabuilding', polish: 'budynek klasy A', english: 'class A building' },
  { ref: 'classbbuilding', polish: 'budynek klasy B', english: 'class B building' },
  { ref: 'classcbuilding', polish: 'budynek klasy C', english: 'class C building' },
  { ref: 'redundantpowersupply', polish: 'Zasilanie zapasowe', english: 'redundant power supply' },
  { ref: 'poured flooring', polish: 'wylana posadzka', english: 'poured flooring' },
  { ref: 'divisionwallsrearrangementpossibility', polish: 'możliwość rearanżacji ścian działowych', english: 'division walls re-arrangement possibility' },
  { ref: 'kitchenette', polish: 'aneks kuchenny', english: 'kitchenette' },
  { ref: 'kitchen', polish: 'kuchnia', english: 'kitchen' },
  { ref: 'electricitypiping', polish: 'instalacja prądowa', english: 'electricity piping' },
  { ref: 'gaspiping', polish: 'instalacja gazowa', english: 'gas piping' },
  { ref: 'waterpiping', polish: 'instalacja wodna', english: 'water piping' },
  { ref: 'exclusivebathroom', polish: 'łazienki na wyłączność', english: 'exclusive bathroom' },
  { ref: 'electricity', polish: 'prąd', english: 'electricity' },
  { ref: 'windowedkitchen', polish: 'kuchnia z oknem', english: 'windowed kitchen' }
]