export const PAGE_TRACK = 'page'
export const PAGE_CREATE_TRACK = 'page/create'
export const PAGE_EDIT_TRACK = 'page/edit'
export const PAGE_SHOW_TRACK = 'page/show'
export const PAGE_INDEX_TRACK = 'page/index'
export const PAGE_INDEX_MANAGE_TRACK = 'page/index/manage'
export const PAGE_INDEX_MAP_TRACK = 'page/index/map'
export const PAGE_NOT_FOUND_TRACK = 'page/not-found'



export const VISITOR_TRACK = 'visitor'
export const VISITOR_PRIVACY_MONIT_TRACK = 'visitor/privacy-monit'
export const VISITOR_COOKIES_POLICY_TRACK = 'visitor/cookies-policy'
export const VISITOR_PRIVACY_SETTINGS_TRACK = 'visitor/privacy-settings'
export const VISITOR_TERMS_OF_SERVICE_TRACK = 'visitor/terms-of-service'
export const VISITOR_PRIVACY_POLICY_TRACK = 'visitor/privacy-policy'
export const VISITOR_CONTACT_TRACK = 'visitor/contact'

export const ANNOUNCEMENT_CREATE_EDIT_TRACK = 'announcement/edit'

export const ANNOUNCEMENT_INDEX_TRACK = 'announcement/index'
export const ANNOUNCEMENT_INDEX_MAP_TRACK = 'announcement/index/map'
export const ANNOUNCEMENT_INDEX_MAP_APARTMENTS_TRACK = 'announcement/index/map/apartments'
export const ANNOUNCEMENT_INDEX_MAP_HOUSES_TRACK = 'announcement/index/map/houses'
export const ANNOUNCEMENT_INDEX_MAP_ROOMS_TRACK = 'announcement/index/map/rooms'
export const ANNOUNCEMENT_INDEX_MAP_PARKING_SPACES_TRACK = 'announcement/index/map/parking-spaces'
export const ANNOUNCEMENT_INDEX_MAP_USABLE_PREMISES_TRACK = 'announcement/index/map/usable-premises'
export const ANNOUNCEMENT_INDEX_MAP_OFFICES_TRACK = 'announcement/index/map/offices'
export const ANNOUNCEMENT_INDEX_MAP_VIRTUAL_OFFICES_TRACK = 'announcement/index/map/virtual-offices'
export const ANNOUNCEMENT_INDEX_MAP_COWORKING_TRACK = 'announcement/index/map/coworking'
export const ANNOUNCEMENT_INDEX_CATALOGUE_TRACK = 'announcement/index/catalogue'
export const ANNOUNCEMENT_INDEX_CATALOGUE_APARTMENTS_TRACK = 'announcement/index/catalogue/apartments'
export const ANNOUNCEMENT_INDEX_CATALOGUE_HOUSES_TRACK = 'announcement/index/catalogue/houses'
export const ANNOUNCEMENT_INDEX_CATALOGUE_ROOMS_TRACK = 'announcement/index/catalogue/rooms'
export const ANNOUNCEMENT_INDEX_CATALOGUE_PARKING_SPACES_TRACK = 'announcement/index/catalogue/parking-spaces'
export const ANNOUNCEMENT_INDEX_CATALOGUE_USABLE_PREMISES_TRACK = 'announcement/index/catalogue/usable-premises'
export const ANNOUNCEMENT_INDEX_CATALOGUE_OFFICES_TRACK = 'announcement/index/catalogue/offices'
export const ANNOUNCEMENT_INDEX_CATALOGUE_VIRTUAL_OFFICES_TRACK = 'announcement/index/catalogue/virtual-offices'
export const ANNOUNCEMENT_INDEX_CATALOGUE_COWORKING_TRACK = 'announcement/index/catalogue/coworking'

export const ANNOUNCEMENT_INDEX_MY_TRACK = 'announcement/index/user'
export const ANNOUNCEMENT_SHOW_TRACK = 'announcement/show'

export const USER_TRACK = 'user'
export const USER_CREATE_TRACK = 'user/create'
export const USER_CREATE_FORM_TRACK = 'user/create/form'
export const USER_CREATE_VERIFICATION_TRACK = 'user/create/verification'
export const USER_EDIT_TRACK = 'user/edit'
export const USER_EDIT_PASSWORD_TRACK = 'user/reset-password'
export const USER_AUTHORIZE_TRACK = 'user/authorize'
export const USER_SHOW_TRACK = 'user/show'
