export const PAGE_TRACK = 'page'
export const PAGE_CREATE_TRACK = 'page/create'
export const PAGE_EDIT_TRACK = 'page/edit'
export const PAGE_SHOW_TRACK = 'page/show'
export const PAGE_INDEX_TRACK = 'page/index'
export const PAGE_INDEX_MANAGE_TRACK = 'page/index/manage'
export const PAGE_INDEX_MAP_TRACK = 'page/index/map'
export const PAGE_NOT_FOUND_TRACK = 'page/not-found'

export const VISITOR_TRACK = 'visitor'
export const VISITOR_PRIVACY_MONIT_TRACK = 'visitor/privacy-monit'
export const VISITOR_COOKIES_POLICY_TRACK = 'visitor/cookies-policy'
export const VISITOR_PRIVACY_SETTINGS_TRACK = 'visitor/privacy-settings'
export const VISITOR_TERMS_OF_SERVICE_TRACK = 'visitor/terms-of-service'
export const VISITOR_PRIVACY_POLICY_TRACK = 'visitor/privacy-policy'
export const VISITOR_CONTACT_TRACK = 'visitor/contact'
